### PR TITLE
Autowig wrappers

### PR DESCRIPTION
**Pull request by pfernique**
Wrappers for stat_tool compile but need to be tested in a IPython terminal

### CODE REVIEW

**Comment by pfernique** [comment]
Plot are now available in the notebook

**Comment by pradal** [comment]
@pfernique : Pierre, is this PR is ready to be merged?
If so, I can do it.

**Comment by pfernique** [comment]
Yes but not in the master !
This branch will be merged in the master when all wrappers for StructureAnalysis packages will be available

**Comment by pradal** [comment]
OK.
Ask me (@pradal) when you want some review and a merge in the master.

**Pull request merged**
